services:
  video_stream:
    build: .
    container_name: video_stream
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "8001:80"
    networks:
      global-net:

  rtsp_server:
    image: bluenviron/mediamtx
    container_name: rtsp_server
    ports:
      - "8554:8554"
    networks:
      global-net:

  rtsp_simulator:
    image: jrottenberg/ffmpeg
    container_name: rtsp_simulator
    volumes:
      - ./videos:/videos
    command: >
      -re -stream_loop -1 -i /videos/video_sample.mp4
             -c copy -f rtsp -rtsp_transport tcp rtsp://rtsp_server:8554/cctv_stream
    depends_on:
      - rtsp_server
    networks:
      global-net:

networks:
  global-net:
    external: true